zigimg/zigimg

- .github/workflows/main.yml
- src/color.zig
- src/format_interface.zig
- src/formats/bmp.zig
- src/formats/netpbm.zig
- src/formats/pcx.zig
- src/image.zig
- src/octree_quantizer.zig
- tests/bmp_test.zig
- tests/color_test.zig
- tests/helpers.zig
- tests/image_test.zig
- tests/netpbm_test.zig
- tests/octree_quantizer_test.zig
- tests/pcx_test.zig
* Allocate Palette on the heap because the static size is too big
* readForImage now accept a *?color.ColorSurface to reduce copying
* Added IntegerColor8 and IntegerColor16 when we need 8-bit or 16-bit Integer color
Closes #37
> Make color.Color use f32 for each color component

- src/format_interface.zig
- src/formats/bmp.zig
- src/formats/pcx.zig
- src/image.zig
- src/utils.zig
This is to help when https://github.com/ziglang/zig/pull/4710 is merged. The thing with `@ptrCast` and anyerror generic types was exploiting undefined behavior (I know you copied the pattern from the std lib, and that had to be changed too).
The diff for GBA is 
```diff
--- a/GBA/assetconverter/image_converter.zig
+++ b/GBA/assetconverter/image_converter.zig
@@ -51,8 +51,7 @@ pub const ImageConverter = struct {
var paletteFile = try openWriteFile(targetPaletteFilePath);
defer paletteFile.close();
-        var paletteOut = paletteFile.outStream();
-        var paletteOutStream = &paletteOut.stream;
+        var paletteOutStream = paletteFile.outStream();
// Write palette file
var paletteCount: usize = 0;
@@ -73,8 +72,7 @@ pub const ImageConverter = struct {
var imageFile = try …
```
> update to latest zig I/O stream changes

- README.md
I don't have easy access to LLVM 10 yet, so I'm not actually on zig's master branch today, but the version of zig referenced in this readme doesn't build with `zig build test`. I used the timestamp of your commits here to guess a version of zig that would work.
> Fix version of zig referenced in README

- src/octree_quantizer.zig
> Replaced deprecated ArrayList.toSlice() with ArrayList.items

- README.md
- src/formats/netpbm.zig
- src/image.zig
Saving and loading in binary format seems to work now. I'm pretty sure saving 16-bit ascii used to work (and it still should) but I haven't tried loading 16-it ascii.
> Add support for 16-bit binary PGM format

- src/formats/pcx.zig
- src/formats/tga.zig
- src/utils.zig
This PR updates zigimg to latest master and tries to fix some usages of `std.fs.File` that will make it work with StreamSource assuming it won't reference std.fs.File on freestanding targets (this will be a companion PR for ziglang)
> Makes zigimg work properly on freestanding targets

- src/image.zig
This PR removes 2 unnecessary calls to `std.fs.path.resolve`, since `openFile` and `createFile` automatically resolve paths.
> Removed unnecessary path resolutions

- src/formats/all.zig
- src/formats/jpeg.zig
- src/image.zig
- zigimg.zig
This is a very basic parser for JPEG images. It currently only supports
baseline DCT JPEG images without chroma subsampling. Various other
things are probably also missing as well, but it's a start. :^)
> formats/jpeg: Add basic decoder for JPEG images

- src/color.zig
- src/formats/jpeg.zig
- src/formats/png.zig
A few functions have been removed from `std.math` as part of https://github.com/ziglang/zig/commit/41dd2beaacade94c5c98400a4a655aea07b9e2f3
> Update to zig master

- src/color.zig
- tests/color_test.zig
Turns out the CSS spec that I was reading was outdated and CSS does support having alpha in their hex string. 
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color
> Add support for alpha in fromHtmlHex function

- src/image.zig
- tests/formats/netpbm_test.zig
- tests/formats/qoi_test.zig
- tests/image_test.zig
It is not needed outside of the test suite and break the purpose of Image to be a format-independant pixel container.
> Remove storage of the image format in Image. 

- gyro.zzz
This pr adds compatibility with the gyro package manager for zig, by adding a gyro.zzz file
> Add gyro (a zig package manager) compatibility

- src/Image.zig
- src/color.zig
- src/format_interface.zig
- src/formats/all.zig
- src/formats/bmp.zig
- src/formats/jpeg.zig
- src/formats/netpbm.zig
- src/formats/pcx.zig
- src/formats/png.zig
- src/formats/png/reader.zig
- src/formats/qoi.zig
- src/formats/tga.zig
- src/pixel_format.zig
- tests/formats/bmp_test.zig
- tests/formats/netpbm_test.zig
- tests/formats/pcx_test.zig
- tests/formats/qoi_test.zig
- tests/formats/tga_test.zig
- tests/image_test.zig
As discusted in the gist: https://gist.github.com/mlarouche/a919a14cb12b01392da0338acd61b997, I needed to have support for animation data in `Image`. With your feedback and from the community I decided to opt for Option 2. 
At the same time, I refactored all format (expect JPEG) `read()` function to return `color.PixelStorage` directly like your PNG code. 
I decided to submit this separately from the GIF read support branch to pay the interface change now and not wait until I've done with GIF read support.
> Refactor Image to support animation

- src/Image.zig
`std.fs.File`s are typically passed around by value. calling `.writer()` does not need it to be a pointer and it is immediately derefererenced
> Image.writeToFile: no need to accept pointer

- src/color.zig
This feels like maybe a bug/regression in Zig, not really an issue in zigimg, but I don't know that for sure. To workaround the issue I also tried elevating the `std.meta.Field` calls outside of the `return struct {}` block inside of `RgbMethods`, but that led to a segfault:
```
slimsag@hexops-ci zigimg % zig build test
error: zigimgtest...
error: The following command terminated unexpectedly:
/Users/slimsag/zig-macos-aarch64-0.11.0-dev.1314+9856bea34/zig test /Users/slimsag/Desktop/hexops/mach-examples/libs/zigimg/zigimg.zig --cache-dir /Users/slimsag/Desktop/hexops/mach-examples/libs/zigimg/zig-cache --global-cache-dir /Users/slimsag/.cache/zig --name zigimgtest --test-no-exec --enable-cache 
error: the following build command failed with exit code 11: …
```
> workaround dependency loop with latest Zig version

- src/formats/qoi.zig
Zig std library change: https://github.com/ziglang/zig/commit/23b7d28896609e3f01765730599119baf53a56c9
> Replace uses of `std.mem.len` with `<array>.len`

- src/formats/png/reader.zig
- src/formats/qoi.zig
Fixes for two issues encountered with zig 0.11.0-dev.1507+6f13a725a building for wasm32.
Saturating arithmetic is broken in llvm (https://github.com/llvm/llvm-project/issues/58557), add workaround
Use .len to find length of fixed sized array, as zig 0.11.0 complains on use of std.mem.len()
> Fix issues encountered with zig 0.11.0/wasm32

- build.zig
The `.kind` field was removed from `std.Build.TestOptions` as part of the recent build API changes.
> Update build.zig for parallel build change

- src/color.zig
- src/formats/png/reader.zig
- src/formats/tga.zig
Recently std.mem.set has been deprecated in favour of @memset.
Version of zig tested: 0.11.0-dev.2935
> Replace std.mem.set with @memset

- src/formats/tga.zig
This commit fixes a compile error generated by Zig 0.11.0-dev.3132
Previously we were calling the reader function (Which takes a mutable pointer) on a temporary TargaStream that was constructed in-place as an argument.
This caused the compile error as all temporary variables are constant. Defining it as an actual variable allows it to be mutable
> Update for zig.0.11.0-dev.3132

- tests/formats/png_test.zig
Hello,
I recently attempted to run tests on my local environment and encountered some issues, which I believe are linked to a recent modification (reference: [PR#15803](https://github.com/ziglang/zig/pull/15803)). I'm working with Zig compiler version 0.11.0-dev.3316+ec58b475b.
Here are the error details I encountered when running `$ zig build test`
```
$ zig build test
zig test zigimgtest Debug native: error: the following command failed with 2 compilation errors:
/snap/zig/7562/zig test /home/argon/workspace/zigimg/zigimg.zig --cache-dir /home/argon/workspace/zigimg/zig-cache --global-cache-dir /home/argon/.cache/zig --name zigimgtest --listen=- 
Build Summary: 0/5 steps succeeded; 1 failed (disable with -fno-summary)
test transitive failure
└─ run zigimgtest transitive failure
├─ zig …
```
> Use snake-case enum

- src/formats/png/chunk_writer.zig
- src/formats/png/reader.zig
- src/formats/qoi.zig
- tests/formats/png_test.zig
- tests/formats/qoi_test.zig
This will port zigimg to Zig master by replacing usage of `std.mem.(copy|set)` with `@mem(copy|set)` and replacing PascalCase enum entries with snake_case enum entries (like #117).
> port to latest zig

- src/Image.zig
isAnimation attempts to access the len field of Animation.frames, but frames is an ArrayListUnmanaged and does not have a len field, instead, the length of the items slice is used.
> fix compile error in Image.isAnimation where nonexistant field was accessed

- src/Image.zig
- zigimg.zig
This catches #119:
```
src/Image.zig:172:34: error: no field named 'len' in struct 'array_list.ArrayListAlignedUnmanaged(src.Image.AnimationFrame,null)'
return self.animation.frames.len > 0;
```
> Change the test block in zigimg.zig to catch more errors like #119

- src/formats/png/chunk_writer.zig
We don't seem to have any encode tests for now, todo?
> fix bug where encoding png would fail because of memcpy sizes being different

- src/formats/netpbm.zig
- enables usage of one common initializer (`.{}`) for all formats
- mirrors the default of libnetpbm and FFmpeg
- smaller
> make binary encoder options the default for netpbm

- src/formats/jpeg.zig
- tests/formats/jpeg_test.zig
This PR is for jpeg sampling factor support.
To achieve the above motivation, this contains the following modifications.
* Perform decoding of AC and DC coefficients for all blocks, which are regions consisting of 8x8 pixels in the MCU
* Increase the size of mcu_storage to support blocks in MCU
* Improve the calculation of the count of MCU for support sampling factor.
* Improve rendering algorithm for support sampling factor.
> Add sampling factor support

- src/formats/jpeg.zig
- tests/formats/jpeg_test.zig
This PR targets adding grayscale JPEG image decoding support.
The key modifications are the followings.
* Make `getBlockCount` and `calculateMCUCountInFrame` handle grayscale images correctly
* Implement `renderToPixelsGrayscale`
`grayscale_sample0.jpg` will be added in the associated PR(https://github.com/zigimg/test-suite/pull/10)
> Add grayscale JPEG image decoding support

- src/formats/pcx.zig
- src/formats/png/InfoProcessor.zig
- src/formats/png/reader.zig
This PR is for catching up with the latest version of zig.
I met the following issues before this PR.
```
$  zig build test
zig test zigimgtest Debug native: error: the following command failed with 3 compilation errors:
/snap/zig/7710/zig test /home/argon/workspace/zigimg/zigimg.zig --cache-dir /home/argon/workspace/zigimg/zig-cache --global-cache-dir /home/argon/.cache/zig --name zigimgtest --listen=-
Build Summary: 0/5 steps succeeded; 1 failed (disable with --summary none)
test transitive failure
└─ run zigimgtest transitive failure
├─ zig test zigimgtest Debug native 3 errors
└─ install transitive failure
└─ install zigimgtest transitive failure
└─ zig test zigimgtest Debug native (reused)
/snap/zig/7710/lib/std/math.zig:437:17: error: deprecated; use @min instead
pub const min = …
```
> Catch up latest zig version

- .github/workflows/main.yml
This PR is for fixing https://github.com/zigimg/zigimg/issues/130 .
https://github.com/zigimg/zigimg/issues/130 is caused by git converting LF to CRLF automatically.
So this PR adds to the configuration to disable this auto CRLF conversion.
This modification is derived from the following comment.
https://github.com/actions/checkout/issues/226#issuecomment-854736025
> diasable autocrlf

- src/formats/png/filtering.zig
Use the new builtin instruction @abs instead of math abs.
Note: this PR should be merged when the 0.12 version of zig is stable, otherwise it could break other projects, on the current master brach this new builtin was added.
> fix: use latest zig abs format

- src/buffered_stream_source.zig
- src/formats/bmp.zig
- src/formats/gif.zig
- src/formats/jpeg.zig
- src/formats/netpbm.zig
- src/formats/pam.zig
- src/formats/pcx.zig
- src/formats/png.zig
- src/formats/png/chunk_writer.zig
- src/formats/png/reader.zig
- src/formats/qoi.zig
- src/formats/tga.zig
- src/utils.zig
- tests/buffered_stream_source_test.zig
- zigimg.zig
Introduce `buffered_stream_source` struct that contains `BufferedStreamSourceReader` and `BufferedStreamSourceWriter`. Both can accept an given buffer size. I also added default ones that use a buffer of 4KiB.
The idea is that we keep using `Image.Stream` in the public API as most as possible but each format implementation is strongly recommended to buffered reader and writers to save on kernel mode calls. 
I timed the test suite using Intel VTune using `zig build test -Doptimize=ReleaseFast` and running the test executable directly.
Before:
After:
Closes #55
> Create buffered wrapper around std.io.StreamSource for reading and writing to buffer I/O

- src/formats/bmp.zig
- src/formats/gif.zig
- src/formats/pcx.zig
- src/formats/png/reader.zig
- src/formats/qoi.zig
- src/formats/tga.zig
- src/utils.zig
Refactor the utils `readStruct`, `writeStruct`, `toMagicNumber` to be consistent with the new `readInt`, `writeInt` API in `std.io`
> Struct utils refactor

- src/formats/gif.zig
- tests/formats/gif_test.zig
Fix integer overflow in GIF and add a test that read the rotating earth GIF from the GIF wikipedia entry
Closes #150
> Fix integer overflow in GIF

- src/formats/png/reader.zig
- tests/formats/png_test.zig
The issue was for the image that has PLTE and  tRNS chunk. PlteProcessor would would modify the destination format to rgba32 but when it came turn for TrnsProcessor to run it would see rgba32 and not do anything. The fix was for TrnsProcessor to look at the source format instead of destination format.
> Fixes #152 loding of trns after plte

- src/formats/png/reader.zig
Png reader used to internally wrap the provided temp_allocator with FixedBufferAllocator so that it can take all the needed memory from it in one allocation and prevent memory fragmentation. This is probably unneeded optimization and it creates a problem now that zig zlib implementation has no fixed bound on memory allocations.
It also returned any error from the decompressor as ImageError.InvalidData so I fixed it so that only InflateErrors are replaced with InvalidData.
> Png out of memory fix

- src/formats/png.zig
- src/formats/png/InfoProcessor.zig
- src/formats/png/reader.zig
Ok, I gave up on having constrained memory usage in png reader until zig std lib fixes their decompressor. This should fix #159 and also not require override of DefaultPngOptions in the main file for big files to work.
> Solved the png reader memory issues

- src/buffered_stream_source.zig
Fix compile error on `self.buffered_reader.start -%= absolute_amt` expected type 'usize', found 'u64' for 32-bit builds, like Wasm.
Copied the solution from the standard library and how they deal with large amount values:
```zig
const abs_amt = @abs(amt);
const abs_amt_usize = std.math.cast(usize, abs_amt) orelse std.math.maxInt(usize);
```
Source: https://github.com/ziglang/zig/blob/bcf4a1391331e52e4a06528530316970ded75c74/lib/std/io/fixed_buffer_stream.zig#L85
> fix compile error for 32-bit builds like Wasm, "self.buffered_reader.start -%= absolute_amt" expected type 'usize', found 'u64

- src/formats/gif.zig
I couldn't build the project for WASM (32-bit) as this is the error I would get:
Presumably this is the same for building to other 32-bit systems.
I am not sure whether my pull request is the right way to do it. I am willing to make changes if there is a better way to do it, this is just what worked for me.
> Fix building on 32-bit systems with valid left-shift size

- src/formats/png/reader.zig
> Add error.EndOfStream to the list of errors handled by zlib decompressor

- src/color.zig
- src/math.zig
- tests/color_test.zig
- tests/helpers.zig
- tests/math_test.zig
- zigimg.zig
Add Colorspace that define a RGB color using CIE xyY color coordinate for red, green, blue and white. Colorspace can convert from gamma-converted to linear and vice-versa. Also Colorspace contains lots of functions to convert to device-inpedendant color spaces 
Added predefined RGB colorspaces:
* sRGB
* Rec. 601 (NTSC,PAL)
* Rec. 709
* BT.2020 (Rec. 2020)
* Adobe RGB
* Adobe Wide Gammut
* ProPhoto RGB
Add the following color models and color spaces:
* HSL,
* HSV
* CMYK
* HSLuv
* CIE XYZ
* CIE L*a*b*
* CIE L*u*v*
* CIE LCh(ab), cylindrical version of CIE Lab
* CIE LCh(uv), cylindrical version of CIE Luv
* Oklab
* OkLCh, cylindrical version of Oklab
Closes #34
> Implement RGB colorspaces and various new color model and color spaces

- src/ImageUnmanaged.zig
- src/color.zig
- src/formats/bmp.zig
- src/formats/png/filtering.zig
- src/formats/png/reader.zig
- src/formats/tga.zig
- src/simd.zig
- src/utils.zig
Zig 0.14 renames a bunch of fields in TypeInfo. This PR addresses that.
I would not merge this until 0.14 is out, since who knows what else gets renamed, but maybe you want to introduce a 0.14 branch or something. Anyway, hope it saves someone else 10 minutes of work.
> #178 - fix for 0.14 TypeInfo changes

- README.md
I'd like to propose updating the installation instructions to use `zig fetch` for adding `zigimg` as a dependency. This would simplify the setup process and reduce some manual steps.
Currently, users have to manually add the dependency and then copy the hash from an error message into `build.zig.zon`. Instead, using `zig fetch --save` could streamline this process by automatically adding the dependency with hash to `build.zig.zon`, making it more user-friendly.
This isn't a major change but could remove some of the hassle and confusion around getting started. Totally understand if it's not something the maintainers want to adopt, but I thought it might be worth considering!
Thanks for your time.
> Proposal: Update installation guide to use `zig fetch --save`

- src/formats/jpeg/utils.zig
Previously code was used to generate the jpeg zigzag values. Instead directly use the zigzag values ala stb_image (stbi__jpeg_dezigzag) and ffmpeg (ff_zigzag_direct).
https://github.com/nothings/stb/blob/5c205738c191bcb0abc65c4febfa9bd25ff35234/stb_image.h#L2194
https://github.com/FFmpeg/FFmpeg/blob/c90e0777da97200c12dd55db7d6e3eb5c6a2cee5/libavcodec/mathtables.c#L98
> jpeg: replace code to compute zigzag with final values

- src/formats/jpeg/utils.zig
The array was not formatted to Zig standards, use `zig fmt: off` to keep it's 8x8 shape.
> jpeg: fix formatting of ZigzagOffsets

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
- src/formats/jpeg/JFIFHeader.zig
- src/formats/jpeg/utils.zig
The primary change is removing the check for JFIF specification since not all JPEGs are JFIFs (JPEG spec is ITU-T87 and JFIF is ITU-T871) https://www.itu.int/rec/T-REC-T.871-201105-I/en.
This can be added in later to parse additional meta data but it shouldn't prevent parsing of non-JFIF spec images.
Additionally this hoists the huffman table parsing to the main marker loop. The Huffman Table definitions can occur in any order between the SOF and SOS header(s). See B.2.4 and Figure B.16 of ITU-T81. This will be needed to support multiple scans (progressive)
> Jpeg rework marker reading

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
- src/formats/jpeg/JFIFHeader.zig
- src/formats/jpeg/Scan.zig
- src/formats/jpeg/utils.zig
In commit e18ed21, Scan was changed to decode & dequantize a single MCU, and then write the to the final pixel destination. This is then repeated for all the MCUs. This coupling is a problem for progressive JPEGs which can write to multiple MCUs at once depending on the number of components in the scan (see A.2.2 of ITU-T81).
Instead:
* place mcu_storage on Frame and have it contain all MCUs for an image (Scan only contained storage for a single MCU). This will increase the memory usage (as prior to e18ed21) but will make progressive JPEG implementation more straightforward.
* decouple dequantize and color conversion -> image writing from decoding of scan -- this makes the code clearer and will make it easier to implement progressive jpegs. 
Note: this stacks on PR …
> jpeg: Undo decoding single MCUs and then writing to image

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
The renderToPixels{Rgb, Grayscale} step loops through the MCUs, processes the pixels, before writing to the final image output. Previously this also included performing the IDCT step. Instead move this to a separate step that is called in the JPEG loop, after dequantizeMCU and before writing.
This is done for two reasons: it decouples performing the IDCT from rendering to the final pixel and for pictures with subsampling this reduces the amount of work done.
With subsampling a single color input pixel will be repeated over multiple final pixels. Since idct is called for every final pixel that's rendered, then for a say, 2x2 downsampled image (for Cr Cb) then we end up calling IDCT 8 times more than necessary on those channels.
> jpeg: separate IDCT from renderToPixels{Grayscale, Rgb}

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
To increase spec compliance, refactor huffman and JFIF checking code.
According to ITU-T81 section B.2.1, a frame header may be proceeded by table specifications. Previously the {ac,dc}_huffman_tables were on the Frame struct and the Frame wasn't initialized until the SOF marker was read. This prevents huffman tables that are specified before SOF from being stored.
Instead move {ac,dc}_huffman_tables to the JPEG struct so huffman tables defined before SOF can be stored. Additionally this moves parseDefineHuffmanTables to JPEG.
Not all JPEGS are JFIF, remove JFIF specific checks in formatDetect.
See 2edb358b1567b1c14213aa3c822d026c062d438f for additional context.
This stacks https://github.com/zigimg/zigimg/pull/196
> Jpeg refactor huffman jfif

- src/formats/jpeg.zig
Addresses comments on https://github.com/zigimg/zigimg/pull/197.
> jpeg: clean up jpeg init and formatDetect

- src/formats/jpeg.zig
Remove unconditional use of std.debug.print(), as this doesn't work on freestanding targets.
Failed on wasm32-freestanding
> Remove unconditional debug

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
- src/formats/jpeg/Scan.zig
- src/formats/jpeg/huffman.zig
- src/formats/jpeg/utils.zig
JPEG: implements spectral selection for progressive jpegs
Implements Spectral Selection for progressive jpegs only (Section G.1.1.1.1) that is, successive approximation (Section G.1.1.1.2) is not implemented.
Other major change was to rename MCU to Block. According to ITU-T81, 3.1.11 the 8x8 array of values is a Block, and MCUs can consist of 1 or more blocks. Rename for clarity.
> JPEG: implements spectral selection for progressive jpegs

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
- src/formats/jpeg/FrameHeader.zig
- src/formats/jpeg/Scan.zig
- tests/formats/jpeg_test.zig
Previously jpeg used `mcu_storage: [][MAX_COMPONENTS][MAX_BLOCKS]Block` where each element contained 1 MCU. When dealing with subsampling (say 2x2) then 1 MCU will contain 4 Luma blocks and 1 of each Cb Cr.
This becomes problematic when dealing progressive jpegs with multiple scans. When each scan contains all components, then performScan can fully fill the MCU before moving to the next MCU. This occurs in the interleaved (ITU-T81, A.2.3) ordering.
However if a scan only contains a single component, then instead of filling a single MCU interleaved order, the scan contains elements per block  (ITU-T81, A.2.2). This results in a difficult fill order where perform scan would need to loop through MCUs multiple times and fill the internal block buffers in an order dictated by the sampling …
> jpeg refactor storage

- src/ImageUnmanaged.zig
- src/formats/all.zig
- src/formats/farbfeld.zig
- tests/formats/farbfeld_test.zig
- zigimg.zig
tried following the conventions I found in qoi.zig and png.zig.
I also added a basic test for reading width and height and reading invalid file.
I did test writing an image but I am still not combortable with the api so I didn't commit that test.
Looking forward for your opinion
> Add support for farbfeld format https://tools.suckless.org/farbfeld/

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
- src/formats/jpeg/Scan.zig
- src/formats/jpeg/huffman.zig
- tests/formats/jpeg_test.zig
JPEG optimizations:
* Use ANN IDCT -- this should probably be changed to the LLM version since that's what's mostly commonly used in JPEG decoders. Using different IDCT methods can cause differences in final output due to rounding. It seems like there's good SIMD implementations as well for LLM https://github.com/libjpeg-turbo/ijg/blob/main/jidctint.c -- Total about >10x speed up for IDCT and 4x total.
* Unroll yCbCrToRgb loop to maximize simd loading. Not sure why this didn't unroll by itself. ~ 25% faster yCbCrToRgb, though the generated code still doesn't seem very good. I'll handroll some simd for this.
* Add acceleration structure based on stb_image. Nearly 50% of run time was huffman decoding and in particularly looking up codes in the AutoArrayHashmap. Instead use an acceleration …
> Jpeg optimizations

- README.md
- src/formats/ilbm.zig
- tests/formats/ilbm_test.zig
This PR adds support for <=8-bit Amiga planar images.
HAM & 24-bit images support is planned.
> Ilbm add indexed planar support

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
- src/formats/jpeg/Scan.zig
- src/formats/jpeg/huffman.zig
- tests/formats/jpeg_test.zig
With restart intervals, when the correct number of MCUs are decoded, we're supposed to flush the remaining bits of the current byte. Previously we just emptied the bit buffer. However since we're now speculatively filling the bit buffer, there may be its that shouldn't be flushed. Instead determine if we're in the middle of a byte and flush rest of the bits in that byte.
> jpeg: fix images with restart interval

- src/formats/jpeg/Scan.zig
- src/formats/jpeg/huffman.zig
Clean up redundant code and loops to improve clarity. For example in progressive both ac first pass and ac successive passes now process skips first instead of one processing skips first and the other skips last.
> Jpeg scan cleanup

- README.md
- src/formats/ilbm.zig
- tests/formats/ilbm_test.zig
This PR adds support for EHB viewmode: it's a special Amiga feature that adds the ability to display 64 colors using only 32 color registers.
> ilbm: add support for EHB files

- src/formats/jpeg.zig
- src/formats/jpeg/Frame.zig
- src/formats/jpeg/utils.zig
JPEGs always are arrays that are multiples of 8x8, for subsampled images, they're also a multiple of the MCU block size, and included in some operations. As such we need to 0 out the non-filled pixels (that is the scan ends before filling the remainder of the frame with 0s.
> jpeg: set values to 0 outside of image boundary

- src/formats/jpeg/Frame.zig
This reverts commit d60c65ec14edda15ec3113f2e36489ea1ef7050f.
I botched the benchmarking, manually unrolling is faster.
Additionally manually doing SIMD is thwarted by the inability to runtime shuffle. Manually attempting to generate the shuffle results in use of vpinserd. The hand unrolled version generates better sequenced vpinserd and is faster.
> Revert unroll yCbCrToRgbBlock"

- src/formats/jpeg/Frame.zig
Accidentally left this in, switched to using inline asm instead.
> jpeg: remove extern llvm instrinsic

- src/formats/jpeg/Frame.zig
- src/formats/jpeg/huffman.zig
- tests/formats/jpeg_test.zig
Ports stb_images LLM IDCT implementation which is based off of `Practical fast 1-D DCT algorithms with 11 multiplications` and named after its authors.
Results in ~20% speed increase in IDCT (1-2% overall)
> jpeg: port LLM IDCT from stb_image

- src/formats/ilbm.zig
- tests/formats/ilbm_test.zig
24-bit & HAM/HAM8 ILBM files don't have any alpha channel so let's use their native pixel format.
No functional change.
> ilbm: use rgb24 pixel format for 24bit/ham/ham8 files

- src/formats/ilbm.zig
- tests/formats/ilbm_test.zig
Adds support for ACBM files: the `BODY` chunk is replaced by `ABIT` chunk that contains the planar image data which is stored plane by plane.
Note that even if the header's compression field is set, the data doesn't appear to be compressed.
> ilbm: add support for acbm files

- README.md
- src/ImageUnmanaged.zig
- src/formats.zig
- src/formats/iff.zig
- tests/formats/iff_test.zig
- tests/image_test.zig
- zigimg.zig
Since we're already supporting ACBM in addition to ILBM IFF forms, and DEEP is also coming, let's rename ILBM to IFF.
> ilbm: rename to ilbm to iff

- src/formats/png/reader.zig
Trying to load the following PNG results in an `InvalidData` error:
Stack trace from project where I was using it:
```
InvalidData
/home/geemili/.cache/zig/p/zigimg-0.1.0-lly-O4heEADSRxoTwJwrD3TBfUob9052sIgb9SL8Iz-A/src/formats/png/reader.zig:372:47: 0x147fd41 in readAllData (seizer-solitaire)
if (result_format != dest_format) return ImageUnmanaged.ReadError.InvalidData;
^
/home/geemili/.cache/zig/p/zigimg-0.1.0-lly-O4heEADSRxoTwJwrD3TBfUob9052sIgb9SL8Iz-A/src/formats/png/reader.zig:242:26: 0x13a6354 in loadWithHeader (seizer-solitaire)
result = try readAllData(&buffered_stream, header, palette, allocator, &options, &chunk_process_data);
^
/home/geemili/.cache/zig/p/zigimg-0.1.0-lly-O4heEADSRxoTwJwrD3TBfUob9052sIgb9SL8Iz-A/src/formats/png/reader.zig:182:21: 0x1330a5e in load …
```
> indexed PNG: use pixel format defined by header

- src/formats/netpbm.zig
- tests/formats/netpbm_test.zig
Return an error when trying to write a pixel format that the Netbpm image format does not support
Fix #189
Fix #131
> Don't write invalid Netpbm images

- src/formats/png.zig
- src/formats/png/reader.zig
- tests/formats/png_test.zig
Write tRNS chunk  for indexed formats only when alpha is present in any of the palette entries. There is a TODO for true color images but that will require futher work on that part.
> PNG: Only write tRNS for indexed formats when alpha is present in the palette

- src/formats/ras.zig
- tests/formats/ras_test.zig
Adds 32bit (xRGB/RGBx) support for Sun Raster format (tests need this [PR](https://github.com/zigimg/test-suite/pull/20)).
> sun: added xRGB32/xBGR32 uncompressed support

- README.md
- src/formats/png.zig
- src/formats/png/filtering.zig
- tests/formats/png_test.zig
Modified the filtering code to support all the pixel formats supported by PNG and now allocates 2 rows of bytes for filtering that require the current and previous row on a image.
> PNG: Write all supported pixel formats

- README.md
- src/formats/sgi.zig
- tests/formats/sgi_test.zig
This was interesting: SGI files use tables to store scanlines compressed data, so two or more lines can share the same compressed data. Better: it's even possible to re-use the same scanline across different channels, for eg. when storing grayscale 16-bit data.
> sgi: add rle compression support

- src/ImageUnmanaged.zig
- src/formats.zig
- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
- tests/image_test.zig
- zigimg.zig
This PR adds preliminary support for decoding [TIFF](https://en.wikipedia.org/wiki/TIFF) files.
- most _baseline_ tags are decoded
- both _little endian_ and _big endian_ files are supported
- only very basic monochrome uncompressed TIFF files can be decoded
- only the first image is decoded (TIFF can contain many)
Note: tests require the sample file added in this [PR](https://github.com/zigimg/test-suite/pull/28) to pass
> Add tiff format

- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
Adds support for grayscale8 uncompressed files.
Note: this PR also fixes a bug in tag decoding: short tags had their value incorrectly shifted to the right which resulted in short tag values be zero. I thought this was ffmpeg producing wrong files but in the future I'd better trust ffmpeg than my code ;)
> tiff: fix short tags decoding, add grayscale8 support

- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
Needs this [PR](https://github.com/zigimg/test-suite/pull/30) for the tests to pass.
> tiff: add 8-bit color_map support

- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
- tests/image_test.zig
Tests need this [PR](https://github.com/zigimg/test-suite/pull/31) to pass.
> Tiff add rgb24 support

- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
This PR fixes a few problems found while attempting to read big-endian tiff files:
- big-endian short tags weren't decoded properly on little endian hosts
- tiff specs states that tag data that is 4 bytes or less is stored directly in the tag's offset field: this includes array of 1 short/long elements
Note: it needs this [PR](https://github.com/zigimg/test-suite/pull/32) for the tests to pass
> tiff: fix big endian conversion + single short/long tag arrays

- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
Needs this [PR](https://github.com/zigimg/test-suite/pull/34) for the tests.
> tiff: add packbits compression support

- README.md
- src/compressions/lzw.zig
- src/formats/gif.zig
- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
Adds LZW decompression support using the already written LZW decompressor that was used in GIF. It had to be slightly modified to work with TIFF.
I also added support for predictor which is often used in combination with LZW.
The tests need this [PR](https://github.com/zigimg/test-suite/pull/36) to pass.
> Tiff add lzw decompression

- README.md
- src/formats/tiff.zig
- src/formats/tiff/types.zig
- tests/formats/tiff_test.zig
This PR adds support for zlib/deflate-compressed tiff files. This is an Adobe extension to TIFF and is apparently common.
Needs this [PR](https://github.com/zigimg/test-suite/pull/37) for the tests.
> tiff: add zlib deflate compression support

- src/compressions/packbits.zig
- src/formats/iff.zig
- src/formats/tiff.zig
Both formats are using the exact same compression algorithm so let's share the code instead of duplicating it!
Apparently _Packbits_ was first used in the original Mac and then re-used by lots of paint applications/formats
of the eighties/early nineties.
> tiff+iff: share packbits compression

- src/formats/sgi.zig
Fix: Building for x86 did not work because of interpreting `u64` as `usize` implicitly in src/formats/sgi.zig. Added a `std.math.cast(usize, ...)`.
> Fix: Building for x86 did not work because of interpreting `u64` as `usize` implicitly in src/formats/sgi.zig.

- README.md
This section of the README was missing a parameter. I also added some comments I would have found useful - assuming they are actually correct...
> docs: fix writeToMemory function signature in README
