src/formats/png.zig
Would close #44 
- Blocked on https://github.com/ziglang/zig/issues/6847
- Need to determine if `std`'s `ZlibStream` API is compatible with zigimg's goals
=> Switch to using zlib from standard library for PNG

src/color.zig, src/formats/bmp.zig, src/formats/netpbm.zig, src/formats/pcx.zig, src/formats/png.zig, src/formats/tga.zig, src/image.zig, src/octree_quantizer.zig
=> Ready for astgen.

src/color.zig, src/formats/jpeg.zig, src/formats/netpbm.zig, src/formats/pcx.zig, src/formats/png.zig, src/formats/qoi.zig, src/formats/tga.zig, src/image.zig, src/octree_quantizer.zig, tests/color_test.zig, tests/formats/bmp_test.zig, tests/formats/jpeg_test.zig, tests/formats/netpbm_test.zig, tests/formats/pcx_test.zig, tests/formats/png_basi_test.zig, tests/formats/png_basn_test.zig, tests/formats/png_bkgd_test.zig, tests/formats/png_misc_test.zig, tests/formats/png_odd_sizes_test.zig, tests/formats/tga_test.zig, tests/image_test.zig, tests/octree_quantizer_test.zig
- Renamed the fields to lowercase
- Renamed fromHtmlHex to fromU32Rgb and added toU32Rgb
- Added fromU32Rgba and toU32Rgba and U64 variants
- Added toArray and fromArray to Colorf32
- Extracted common Rgba code to mixins RgbMethods and RgbaMethods
- Added toPremultipliedAlpha() to Rgba colors
=> Refactor the color code

src/formats/jpeg.zig
=> remove unnecessary discard

README.md, build.zig, src/formats/tga.zig, tests/formats/tga_test.zig, tests/image_test.zig
* Add support for reading TGA version 1 that does not have a valid footer
* Add support for the bottom-to-top flag.
* Cleanup TODO in tga.zig
Fixes #112
=> Fix various TGA issues

src/Image.zig, src/formats/all.zig, src/formats/pam.zig, tests/formats/pam_test.zig, zigimg.zig
=> Portable Arbitrary Map

src/formats/jpeg.zig
This PR targets memory usage optimization during JPEG decoding. (https://github.com/zigimg/zigimg/issues/127)
The key modifications include:
* MCUs are now decoded and rendered one by one, enhancing memory efficiency.
* The mcu_storage allocation has been eliminated.
* Certain functions have been shifted from Frame to Scan to better align with their responsibilities.
* The parsing of scan frames is now initiated from the main loop in the read function of the JPEG struct.
=> Improve memory usage of jpeg decoding

README.md, src/color.zig, src/formats/bmp.zig, src/formats/jpeg.zig, src/formats/netpbm.zig, src/formats/pam.zig, src/formats/pcx.zig, src/formats/png.zig, src/formats/png/InfoProcessor.zig, src/formats/png/chunk_writer.zig, src/formats/png/filtering.zig, src/formats/png/reader.zig, src/formats/png/types.zig, src/formats/png/zlib_compressor.zig, src/formats/qoi.zig, src/formats/tga.zig, src/octree_quantizer.zig, src/utils.zig
New zig version contains a lot of breaking changes, this uses the automated conversion through zig fmt to update, with a couple manual cleanups where the conversion failed to produce working code.
=> Update to latest zig and update readme

README.md, src/formats/all.zig, src/formats/pcx.zig, src/simd.zig, tests/formats/pcx_test.zig
Add support for writing PCX format
Closes #8
=> Write PCX format 

README.md, src/Image.zig, src/color.zig, src/formats/all.zig, src/formats/gif.zig, src/formats/pam.zig, src/formats/png.zig, src/formats/png/reader.zig, src/formats/tga.zig, src/pixel_format.zig, src/simd.zig, src/utils.zig, tests/formats/tga_test.zig, tests/pixel_format_test.zig, zigimg.zig
=> Add Write TGA support 

src/formats/png/filtering.zig
> At least on my machine this runs faster. My guess is that this speeds up the heuristic computation by reducing the number of cache misses for PNG images that are very wide.
This PR splits out one of the changes from #138. I decided to start with this change since it is very simple.
=> perf: compute filter heuristic in one pass

build.zig
=> Make this work with zig 0.12.0-dev.2058+04ac028a2

src/formats/png/reader.zig
found this while updating my project
=> Fix memory leak in png read

build.zig.zon, src/Image.zig, src/formats/png.zig, src/formats/png/InfoProcessor.zig, src/formats/png/filtering.zig, src/formats/png/reader.zig, src/formats/png/zlib_compressor.zig
Update all zlib related calls to conform to the new API. Add a build.zig.zon which is required by the package manager now.
=> zlib: update for latest zig api and add build.zig.zon

src/Image.zig
=> Update to Zig 0.12.0

.github/workflows/main.yml, .gitignore, README.md, build.zig, src/Image.zig, src/formats/png/chunk_writer.zig, tests/buffered_stream_source_test.zig, tests/color_test.zig
These were the changes needed to update zigimg to 0.13.0-dev.351+64ef45eb0 ([Zig 2024.05](https://github.com/hexops/mach/issues/1180))
Just sending in case helpful, feel free to close if not.
=> update to Zig 0.13.0-dev.351+64ef45eb0

src/FormatInterface.zig, src/Image.zig, src/ImageUnmanaged.zig, src/color.zig, src/formats/bmp.zig, src/formats/gif.zig, src/formats/jpeg.zig, src/formats/netpbm.zig, src/formats/pam.zig, src/formats/pcx.zig, src/formats/png.zig, src/formats/png/reader.zig, src/formats/qoi.zig, src/formats/tga.zig, tests/formats/pam_test.zig, tests/formats/png_test.zig, tests/image_test.zig, zigimg.zig
* Add ImageUnmanaged, same as Image but does not store the allocator
* Add Image.fromRawPixelsOwned(), ImageUnmanaged.fromRawPixelsOwned() and ImageUnmanaged.fromRawPixels()
=> Add ImageUnmanaged that does not store the allocator

.github/workflows/main.yml, README.md, src/ImageUnmanaged.zig, src/color.zig, src/compressions/lzw.zig, src/formats/bmp.zig, src/formats/png/filtering.zig, src/formats/png/reader.zig, src/formats/tga.zig, src/math.zig, src/simd.zig, src/utils.zig
Picks up changes from #180 plus some others
=> Update to 2024.10.0-mach (zig 0.14.0 dev.1911+3bf89f55c)

src/formats/jpeg/Scan.zig, src/formats/pcx.zig, src/formats/png/reader.zig, src/formats/tga.zig, tests/formats/png_test.zig
Fixes #184. Also done zig fmt on other files.
=> Fixed memory alias issue in png reader

src/utils.zig
Found a couple more places where this change hadn't been made
=> fix for 0.14

src/formats/jpeg/Scan.zig
Implements successive approximation in progressive jpegs (ITU-T81, clause G.1.2.3).
Slightly modifies previous written code for spectral selection only, in order to make the code more closely align with the procedure for spectral selection (improve clarity when reading).
Subsampled currently does not work since the interleaving is not properly handled in the subsample code.
Nit: renames mcu to block in decDCCoefficient.
=> jpeg: implement successive approximation (no subsampling)

src/formats/jpeg.zig, src/formats/jpeg/Frame.zig, src/formats/jpeg/FrameHeader.zig, src/formats/jpeg/Scan.zig, tests/formats/jpeg_test.zig
Subsampling requires that if luminance is in a separate scan, to follow non-interleaved ordering.
Stacks https://github.com/zigimg/zigimg/pull/210
=> Jpeg progressive subsampling

src/formats/jpeg/Frame.zig
Address comments in https://github.com/zigimg/zigimg/pull/210
=> jpeg: switch to lowercase function name

README.md, src/PixelFormatConverter.zig, src/color.zig, src/formats/pam.zig, src/pixel_format.zig, tests/color_test.zig, tests/image_test.zig, tests/pixel_format_converter_test.zig
Rgb332 comes in handy for embedded systems with small scale TFT and memory limitations. 
First time zig commit so bear with me :)
=> Add new pixel format: Rgb332

src/formats/jpeg/Frame.zig, src/simd.zig
Requires manually calling vpermd in order to generate code more efficient than manually unrolling.
Previously the code would just inline any function that generated vpermd and then convert it to using vpinsrd. Instead directly call the instrinsic if AVX2 is supported.
=> jpeg: simd for ycbcr to rgb conversion

src/formats/iff.zig
This PR paves the way to IFF-DEEP support:
- the header is now a union tag
- moved bmhd chunk into specific function
No functional change: deep file loading should come in the next PR.
=> iff: cleanup code and add some iff-deep chunks

build.zig, src/formats/png.zig, src/formats/png/InfoProcessor.zig, src/formats/png/reader.zig, tests/formats/png_test.zig
=> Fixed png.PlteProcessor and changed its defaults not to use it

README.md
https://github.com/zigimg/zigimg/issues/242
=> update readme with JPEG support

README.md, src/ImageUnmanaged.zig, src/formats.zig, src/formats/ras.zig, src/utils.zig, tests/formats/ras_test.zig, tests/image_test.zig, zigimg.zig
This PR adds preliminary suport for [SUN Raster](https://en.wikipedia.org/wiki/Sun_Raster) images.
=> Add sun raster format

src/formats/ras.zig, tests/formats/ras_test.zig
Need this [PR](https://github.com/zigimg/test-suite/pull/21) for the tests.
=> Ras add 8bit color support

README.md, src/formats/ras.zig, tests/formats/ras_test.zig
Tests needs this [PR](https://github.com/zigimg/test-suite/pull/24) to pass.
This is all that I'm planning to implement for Sun Raster images :)
=> Sun add rle compression support

src/Image.zig, src/ImageEditor.zig, src/ImageUnmanaged.zig, tests/image_editor_test.zig, zigimg.zig
This PR adds vertical flipping from #139.
=> Add vertical flipping

src/compressions/ccitt.zig, src/formats/tiff/types.zig
Some small code improvements following my latest TIFF PR.
=> tiff: small changes to improve code quality

README.md
Let's make it clear TIFF is at least partially supported :)
=> doc: added tiff section
